// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Teste1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void teste1() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1376, 744));
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    driver.findElement(By.cssSelector(".MuiBox-root-24 > .MuiTypography-root")).click();
    driver.findElement(By.id("descricao")).click();
    driver.findElement(By.id("descricao")).sendKeys("testando1234567");
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    driver.findElement(By.cssSelector(".MuiBox-root-18 > .MuiTypography-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btnModal > .MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".btnModal > .MuiButton-label")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("titulo")).click();
    driver.findElement(By.id("titulo")).sendKeys("teste33333333");
    driver.findElement(By.id("texto")).click();
    driver.findElement(By.id("texto")).sendKeys("aaaaaaaaaaaahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh");
    {
      WebElement element = driver.findElement(By.id("demo-simple-select-helper"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(6)")).click();
    driver.findElement(By.cssSelector("form")).click();
    {
      WebElement element = driver.findElement(By.id("demo-simple-select-helper"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".Mui-selected"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".Mui-selected")).click();
    driver.findElement(By.cssSelector(".botaoFinalizarPostagem > .MuiButton-label")).click();
    driver.findElement(By.cssSelector(".MuiBox-root-293 .MuiButton-label")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".botaoSim"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".botaoSim")).click();
    driver.findElement(By.cssSelector(".MuiBox-root-22 > .MuiTypography-root")).click();
    driver.findElement(By.cssSelector(".MuiBox-root-423 .MuiButton-label")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".botaoSim > .MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".botaoSim > .MuiButton-label")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBox-root-481 .MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiBox-root-481 .MuiButton-label")).click();
    driver.findElement(By.cssSelector(".botaoSim > .MuiButton-label")).click();
    driver.findElement(By.cssSelector(".MuiBox-root-26 > .MuiTypography-root")).click();
    driver.findElement(By.id("usuario")).sendKeys("teste@teste.com");
    driver.findElement(By.id("senha")).sendKeys("123456789");
  }
}
